
image: python:3.10.5-slim-buster

lint:
  script:
    - pip install clang-format==17.0.6
    - changes_detected=0; for file in $(find . -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.cxx" -o -name "*.h" -o -name "*.hpp" -o -name "*.cu" \)); do clang-format --dry-run --Werror "$file"; if [ $? -ne 0 ]; then changes_detected=1; fi; done; if [ $changes_detected -eq 1 ]; then echo "clang-format made changes to some files."; exit 1; else echo "No changes made by clang-format."; fi
  allow_failure: false



pages:
  before_script:
    - apt-get update
    - apt-get install doxygen python3-sphinx clang -y
    - pip install sphinx-rtd-theme breathe sphinx-sitemap myst_parser hawkmoth clang sphinx-copybutton
  script:
    - cd documentation/docs_sphinx
    - make html
    - mv _build/html ../../public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

