// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include <Arduino.h>  // Required for Serial in the global_event_handler
///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;
#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0
// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_global_event_handler(lv_event_t * e) {
    // Empty handler - we're using the custom handler in the .ino file
}
             


///////////////////// SCREENS ////////////////////

static void load_screen2_cb(lv_timer_t * timer)
{
    LV_UNUSED(timer);
    lv_disp_load_scr(ui_Screen2);
}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_ScreenClock_screen_init(); // Only call, do not define here
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    
    // Make screens properly handle touch events
    lv_obj_add_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_Screen3, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_ScreenClock, LV_OBJ_FLAG_CLICKABLE);
    
    // Note: Custom touch handler will be added in the .ino file
    
    // Load Screen2 initially after a brief delay (without creating recurring timer)
    lv_timer_t * one_time_timer = lv_timer_create(load_screen2_cb, 2000, NULL);
    lv_timer_set_repeat_count(one_time_timer, 1); // Run only once
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy(); // Only call, do not define here
    ui_Screen2_screen_destroy(); // Only call, do not define here
    ui_Screen3_screen_destroy(); // Only call, do not define here
    // ui_ScreenClock_screen_destroy(); // Not defined, do not call
}
