// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H


#include "lvgl.h"
#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_ScreenClock.h"

#ifdef __cplusplus
extern "C" {
#endif

// Global event handler for gestures
void ui_global_event_handler(lv_event_t * e);

// Debug function for touch events
void my_touch_cb(lv_event_t * e);

// WiFi connection function
void connect_to_wifi(const char* ssid, const char* password);

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_cowlar_logo_png);    // assets/cowlar logo.png
LV_IMG_DECLARE(ui_img_cowlar_logo1_png);    // assets/cowlar logo1.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
