// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"


#ifdef __cplusplus
extern "C" {
#endif


void stop_alert(lv_event_t * e)
{
	// Your code here
}

#ifdef __cplusplus
}
#endif

void my_touch_cb(lv_event_t * e) {
   
}
