#ifdef __cplusplus
extern "C" {
#endif

// C-callable wrapper for MQTT publish for OK button (implemented in .ino)
void publish_okbtn_state(int state);

#ifdef __cplusplus
}
#endif
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void stop_alert(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
