// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include <string.h>
#include <Arduino.h>

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_Label5_wifi = NULL;
lv_obj_t * ui_Label6_wifi = NULL;
lv_obj_t * ui_Label7_wifi = NULL;
lv_obj_t * ui_TextArea1 = NULL;   // SSID TextArea
lv_obj_t * ui_TextArea2 = NULL;   // Password TextArea
lv_obj_t * ui_ConnectButton = NULL; // Connect Button
lv_obj_t * ui_StatusLabel = NULL;  // Status Label
lv_obj_t * ui_Keyboard = NULL;  // Keyboard for text input
lv_obj_t * ui_WifiIcon = NULL;   // WiFi connection icon

// Store the original positions of UI elements
int16_t original_connect_btn_y = 0;
int16_t original_status_label_y = 0;
bool positions_stored = false;
// These variables are accessed from the main sketch as well

// Forward declaration of keyboard event handler
static void keyboard_event_cb(lv_event_t * e);

// event funtions
// Keyboard handler for LVGL 9.x
static void keyboard_event_cb(lv_event_t * e) 
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * kb = lv_event_get_target(e);
    
    extern unsigned long last_touch_time;
    static bool keyboard_was_visible = false;
    if(code == LV_EVENT_READY) {
        if (keyboard_was_visible) {
            last_touch_time = millis(); // Reset inactivity timer only if keyboard was visible
            keyboard_was_visible = false;
        }
        // Enter key was pressed
        lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
        lv_keyboard_set_textarea(kb, NULL);
        
        // Clear focus on all textareas
        lv_obj_clear_state(ui_TextArea1, LV_STATE_FOCUSED);
        lv_obj_clear_state(ui_TextArea2, LV_STATE_FOCUSED);
        
        // Restore status label position
        lv_obj_set_y(ui_StatusLabel, original_status_label_y);
        
        // Show Connect button if BOTH fields have text
        const char* ssid_text = lv_textarea_get_text(ui_TextArea1);
        const char* password_text = lv_textarea_get_text(ui_TextArea2);
        
        if (strlen(ssid_text) > 0 && strlen(password_text) > 0) {
            lv_obj_clear_flag(ui_ConnectButton, LV_OBJ_FLAG_HIDDEN);
            lv_obj_set_y(ui_ConnectButton, original_connect_btn_y);
        }
    }
    else if(code == LV_EVENT_CANCEL) {
        if (keyboard_was_visible) {
            last_touch_time = millis(); // Reset inactivity timer only if keyboard was visible
            keyboard_was_visible = false;
        }
        lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
        lv_keyboard_set_textarea(kb, NULL);
    }
    else if(code == LV_EVENT_VALUE_CHANGED) {
        // Handle key press
        lv_obj_t* ta = lv_keyboard_get_textarea(kb);
        if(ta != NULL) {
            // Keyboard is working - we don't need logging here
        }
    }
}

// Textarea event callback
void textarea_event_cb(lv_event_t * e)
{
    lv_obj_t * ta = lv_event_get_target(e);
    lv_event_code_t code = lv_event_get_code(e);
    
    if(code == LV_EVENT_FOCUSED || code == LV_EVENT_CLICKED) {
        extern unsigned long last_touch_time;
        static bool keyboard_was_visible = false;
        last_touch_time = millis(); // Reset inactivity timer when keyboard is shown
        keyboard_was_visible = true;
        // Store original positions if first time
        if (!positions_stored) {
            original_connect_btn_y = lv_obj_get_y(ui_ConnectButton);
            original_status_label_y = lv_obj_get_y(ui_StatusLabel);
            positions_stored = true;
        }
        
        // Hide Connect button while typing
        lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_HIDDEN);
        
        // Always hide the status label when showing keyboard (wifi status will be shown by global icon)
        lv_obj_add_flag(ui_StatusLabel, LV_OBJ_FLAG_HIDDEN);
        
        // Store position of status label
        lv_obj_set_y(ui_StatusLabel, -70);
        
        // Show keyboard and attach it to the textarea
        lv_keyboard_set_textarea(ui_Keyboard2, ta);
        lv_obj_clear_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);
        lv_obj_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID, 0, 0);
        
        // Set focus to the textarea
        lv_obj_add_state(ta, LV_STATE_FOCUSED);
    }
    else if(code == LV_EVENT_DEFOCUSED) {
        // Check if another text area is focused
        if (lv_obj_has_state(ui_TextArea1, LV_STATE_FOCUSED) || 
            lv_obj_has_state(ui_TextArea2, LV_STATE_FOCUSED)) {
            return;  // Don't hide keyboard if moving between text areas
        }
        
        // Hide keyboard
        lv_keyboard_set_textarea(ui_Keyboard2, NULL);
        lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);
        
        // Restore original position for status label
        lv_obj_set_y(ui_StatusLabel, original_status_label_y);
        
        // Don't hide the status label - it will be managed by the WiFi connection code
        
        // Show Connect button only if BOTH fields have text
        const char* ssid_text = lv_textarea_get_text(ui_TextArea1);
        const char* password_text = lv_textarea_get_text(ui_TextArea2);
        
        if (strlen(ssid_text) > 0 && strlen(password_text) > 0) {
            // Show the button in its original position
            lv_obj_clear_flag(ui_ConnectButton, LV_OBJ_FLAG_HIDDEN);
            lv_obj_set_y(ui_ConnectButton, original_connect_btn_y);
        }
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Create keyboard and initially hide it
    ui_Keyboard2 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard2, LV_PCT(100));  // Full width
    lv_obj_set_height(ui_Keyboard2, LV_VER_RES / 2); // Half the screen height
    lv_obj_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID, 0, 0); // Align to bottom
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);  // Hide keyboard initially
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_TEXT_LOWER); // Set to text mode
    lv_keyboard_set_popovers(ui_Keyboard2, true); // Enable popovers for better typing experience
    lv_obj_add_event_cb(ui_Keyboard2, keyboard_event_cb, LV_EVENT_ALL, NULL);

    ui_Label5_wifi = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5_wifi, -10);
    lv_obj_set_y(ui_Label5_wifi, -109);
    lv_obj_set_align(ui_Label5_wifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5_wifi, "WiFi Setup");

    ui_Label6_wifi = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label6_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6_wifi, -79);
    lv_obj_set_y(ui_Label6_wifi, -94);
    lv_obj_set_align(ui_Label6_wifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6_wifi, "SSID");

    ui_Label7_wifi = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label7_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7_wifi, -78);
    lv_obj_set_y(ui_Label7_wifi, -49);
    lv_obj_set_align(ui_Label7_wifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7_wifi, "Password");

    // SSID text field
    ui_TextArea1 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea1, 200);
    lv_obj_set_height(ui_TextArea1, 30);
    lv_obj_set_x(ui_TextArea1, -2);
    lv_obj_set_y(ui_TextArea1, -72);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Enter WiFi Name");
    lv_obj_add_flag(ui_TextArea1, LV_OBJ_FLAG_CLICKABLE); // Make sure it's clickable
    lv_obj_add_flag(ui_TextArea1, LV_OBJ_FLAG_CLICK_FOCUSABLE); // Ensure it can be focused by clicking
    lv_obj_add_event_cb(ui_TextArea1, textarea_event_cb, LV_EVENT_ALL, NULL); // Listen to all events

    // Password text field
    ui_TextArea2 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea2, 200);
    lv_obj_set_height(ui_TextArea2, 30);
    lv_obj_set_x(ui_TextArea2, -4);
    lv_obj_set_y(ui_TextArea2, -22);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Enter Password");
    lv_textarea_set_password_mode(ui_TextArea2, true);
    lv_obj_add_flag(ui_TextArea2, LV_OBJ_FLAG_CLICKABLE); // Make sure it's clickable
    lv_obj_add_flag(ui_TextArea2, LV_OBJ_FLAG_CLICK_FOCUSABLE); // Ensure it can be focused by clicking
    lv_obj_add_event_cb(ui_TextArea2, textarea_event_cb, LV_EVENT_ALL, NULL); // Listen to all events
    
    // Add Connect Button - position it between the password field and bottom of screen
    ui_ConnectButton = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ConnectButton, 120);
    lv_obj_set_height(ui_ConnectButton, 40);
    lv_obj_set_x(ui_ConnectButton, 0);
    lv_obj_set_y(ui_ConnectButton, -10);  // Move it closer to the password field
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_CENTER);
    
    // Set button color to orange
    lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // Add darker orange for pressed state
    lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0xDD6600), LV_PART_MAIN | LV_STATE_PRESSED);
    
    // Hide button initially until user enters credentials
    lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_HIDDEN);
    
    // We don't add an event handler here - it will be added in the main sketch
    
    lv_obj_t * btn_label = lv_label_create(ui_ConnectButton);
    lv_label_set_text(btn_label, "Connect");
    lv_obj_center(btn_label);
    
    // Add Status Label - position it below the Connect button
    ui_StatusLabel = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_StatusLabel, 220);
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StatusLabel, 0);
    lv_obj_set_y(ui_StatusLabel, 60);  // Position below connect button, adjusted for new button position
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusLabel, "");
    lv_obj_set_style_text_align(ui_StatusLabel, LV_TEXT_ALIGN_CENTER, 0);
    
    // Add a background to make the text more readable
    lv_obj_set_style_bg_color(ui_StatusLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusLabel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_StatusLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_StatusLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // Hide status label initially - only show when connect button is pressed
    lv_obj_add_flag(ui_StatusLabel, LV_OBJ_FLAG_HIDDEN);
    
    // Create WiFi icon using a label with a WiFi symbol
    ui_WifiIcon = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_WifiIcon, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_WifiIcon, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_WifiIcon, 80);  // Position to the right of the status text
    lv_obj_set_y(ui_WifiIcon, 30);  // Above the status label
    lv_obj_set_align(ui_WifiIcon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiIcon, LV_SYMBOL_WIFI);  // WiFi symbol
    lv_obj_set_style_text_font(ui_WifiIcon, &lv_font_montserrat_24, 0); // Larger font for icon
    lv_obj_set_style_text_color(ui_WifiIcon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT); // Gray color when not connected
    // Hide WiFi icon initially
    lv_obj_add_flag(ui_WifiIcon, LV_OBJ_FLAG_HIDDEN);
}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Keyboard2 = NULL;
    ui_Label5_wifi = NULL;
    ui_Label6_wifi = NULL;
    ui_Label7_wifi = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_ConnectButton = NULL;
    ui_StatusLabel = NULL;
    ui_Keyboard = NULL;
    ui_WifiIcon = NULL;
}
