// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H


#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label5_wifi;
extern lv_obj_t * ui_Label6_wifi;
extern lv_obj_t * ui_Label7_wifi;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_ConnectButton;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_WifiIcon;
// Function declarations
void textarea_event_cb(lv_event_t * e);
// Shared variables
extern int16_t original_connect_btn_y;
extern int16_t original_status_label_y;
extern bool positions_stored;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

// Access WiFi connection state (C++ linkage only)
extern bool wifi_connecting;

#endif

