// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_okbtn = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_timer = NULL;
// --- OK button timer for MQTT state ---
static lv_timer_t * okbtn_timer = NULL;

// Timer callback to send 0
static void okbtn_send_zero_cb(lv_timer_t * timer) {
    // Defensive: Only publish if still on Screen2
    extern lv_obj_t * ui_Screen2;
    if (lv_scr_act() == ui_Screen2) {
        publish_okbtn_state(0);
    }
    lv_timer_del(timer);
    okbtn_timer = NULL;
}

// event functions
void ui_event_okbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_PRESSED) {
        // Send 1 to MQTT topic alert/watchok (call C++ wrapper)
        publish_okbtn_state(1);
        // stop_alert(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        // After 1 second, send 0 to MQTT topic alert/watchok (call C++ wrapper)
        if (okbtn_timer) {
            lv_timer_del(okbtn_timer);
            okbtn_timer = NULL;
        }
        okbtn_timer = lv_timer_create(okbtn_send_zero_cb, 1000, NULL);
    }
}





// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_GESTURE_BUBBLE);
    lv_obj_add_flag(ui_Screen2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_okbtn = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_okbtn, 100);
    lv_obj_set_height(ui_okbtn, 50);
    lv_obj_set_x(ui_okbtn, -1);
    lv_obj_set_y(ui_okbtn, 72);
    lv_obj_set_align(ui_okbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_okbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_okbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    // Set button color to orange
    lv_obj_set_style_bg_color(ui_okbtn, lv_color_hex(0xFF8800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_okbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // Add darker orange for pressed state
    lv_obj_set_style_bg_color(ui_okbtn, lv_color_hex(0xDD6600), LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image5 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image5, &ui_img_cowlar_logo1_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image5, -3);
    lv_obj_set_y(ui_Image5, -82);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -3);
    lv_obj_set_y(ui_Label3, 72);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "OK");

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -4);
    lv_obj_set_y(ui_Label4, -36);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24, 0);
    lv_label_set_text(ui_Label4, "Time to Reach");

    ui_timer = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_timer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timer, -2);
    lv_obj_set_y(ui_timer, 1);
    lv_obj_set_align(ui_timer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timer, "waiting for alert...");

    lv_obj_add_event_cb(ui_okbtn, ui_event_okbtn, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // Cancel OK button timer if running
    if (okbtn_timer) {
        lv_timer_del(okbtn_timer);
        okbtn_timer = NULL;
    }

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_okbtn = NULL;
    ui_Image5 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_timer = NULL;

}
